### ISSUE TITLE
.gitignore 中代码重复

### ISSUE THREAD

**Issue by niubx** [gogf/template-single#2]
第 8 行与第 16 行代码重复
<img width="338" alt="图片" src="https://user-images.githubusercontent.com/47147939/153354411-d0ea3639-bec6-49e1-af73-eb895053ed7e.png">
其他仓库如 [gf](https://github.com/gogf/gf)/.gitignore 与 [template-mono](https://github.com/gogf/template-mono)/.gitignore 同样存在此问题

**Comment by houseme** [comment]
https://github.com/gogf/template-single/pull/4

**Comment by houseme** [comment]
https://github.com/gogf/gf/pull/1684
